version: "3.3"
services:
  validator:
    build: ./validator
    links:
      - mysql1
    networks:
      - my-net
    ports:
      - "8080:8080"
  mysql1:
    image: mysql:5.7
    ports:
      - "3306:3306"
    networks:
      - my-net
    environment:
      MYSQL_HOST: mysql1
      MYSQL_USER: sa
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: UID
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./validatorDB:/docker-entrypoint-initdb.d/:ro
      
networks:
  my-net:
